fixup "fb_sdl: update to use sdl2" (add missing INC_DIR)
Required on Ubuntu 20.04 (at least).

  /usr/include/x86_64-linux-gnu/SDL2/SDL_platform.h:179:10: fatal error: begin_code.h: No such file or directory

  libsdl2-dev: Installed: 2.0.10+dfsg1-3

  > pkg-config --cflags sdl2
  -D_REENTRANT -I/usr/include/SDL2

Issue #4993