ldso: ignore undefined weak non-function symbols on riscv
When executing

make KERNEL=hw BOARD=virt_qemu_riscv TEST_PKGS=test-stdcxx TEST_SRCS= run/depot_autopilot

we experience errors like

Error: LD: symbol not found: 'transaction clone for operator new[](unsigned long)'

This issue seems to be caused by weak undefined symbols of libitm and
seems to be related to
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=119369. On x86 these
symbols will end as undefined functions causing R_JUMP_SLOT relocation.
Because the functions are not called, there is no problem.  On RISC-V
these symbols have no type, they are not functions and R_RISCV_64
relocations are emitted by binutils-ld. These relocations are used for
global data and resolved during library load, by searching the loaded
library only. Because the symbol cannot be resolved the test fails.

This commit ignores undefined weak symbols for R_RISCV_64 relocations
during program load.

It should be reverted after a tool chain/binutils update if possible.

issue #5607